/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ZombiesGame.GUI;

import GameClasses.Defense;
import GameClasses.Enemy;
import GameClasses.Game;
import ZombiesGame.GUI.GameControl.BoardMarks.Board;
import ZombiesGame.GUI.GameControl.Settings;
import ZombiesGame.GUI.GameControl.adm.Control;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.*;

/**
 *
 * @author Esteb
 */
public class GUIGAME extends javax.swing.JFrame {
    Control control = new Control();
    Game.GameBuilder gameBuilder = new Game.GameBuilder();
    /**
     * Creates new form GUIGAME
     */
    public GUIGAME() {
        //TODO: SOLICITRAR AL USUARIO EL NOMBRE DEL JUEGO MEDIANTE UN JOptionPane
        initComponents();
        setTitle("Compilador C"); 
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        initBoard();
        jPanelGame.setLayout( new GridLayout(1,2));
        jPanelGame.add(jPanelBoard);
        jPanelGame.add(jPanelControls);
        SpinnerModel xmodel = new SpinnerNumberModel(0, 0, 24, 1);
        SpinnerModel ymodel = new SpinnerNumberModel(0, 0, 24, 1);
        jSpinnerX.setModel(xmodel);
        jSpinnerY.setModel(ymodel);
        jSpinnerX.setEnabled(false);
        jSpinnerY.setEnabled(false);
        pintarImagen(jPanelBG, Settings.BACKGROUND);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanelBG = new javax.swing.JPanel();
        jPanelGame = new javax.swing.JPanel();
        jPanelBoard = new javax.swing.JPanel();
        jPanelBoardSquares = new javax.swing.JPanel();
        jPanelBoardY = new javax.swing.JPanel();
        jPanelBoardX = new javax.swing.JPanel();
        jPanelControls = new javax.swing.JPanel();
        jButtonExport = new javax.swing.JButton();
        jButtonLoadGame = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jButtonLevelUp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelBuildingsAvailable = new javax.swing.JLabel();
        jComboBoxBuildings = new javax.swing.JComboBox<>();
        jButtonPut = new javax.swing.JButton();
        jSpinnerX = new javax.swing.JSpinner();
        jLabelXCoord = new javax.swing.JLabel();
        jLabelYCoord = new javax.swing.JLabel();
        jSpinnerY = new javax.swing.JSpinner();
        jPanelImageSelectedBuilding = new javax.swing.JPanel();
        jButtonCargarDefensas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelEnemies = new javax.swing.JLabel();
        jButtonCargarEnemigos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonIniciarNueva = new javax.swing.JButton();
        jLabelName = new javax.swing.JLabel();
        jPanelTitlePane = new javax.swing.JPanel();
        jLabelTitle1 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGame.setBackground(new java.awt.Color(255, 255, 204));

        jPanelBoard.setBackground(new java.awt.Color(102, 255, 51));

        jPanelBoardSquares.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanelBoardSquaresLayout = new javax.swing.GroupLayout(jPanelBoardSquares);
        jPanelBoardSquares.setLayout(jPanelBoardSquaresLayout);
        jPanelBoardSquaresLayout.setHorizontalGroup(
            jPanelBoardSquaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelBoardSquaresLayout.setVerticalGroup(
            jPanelBoardSquaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jPanelBoardY.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout jPanelBoardYLayout = new javax.swing.GroupLayout(jPanelBoardY);
        jPanelBoardY.setLayout(jPanelBoardYLayout);
        jPanelBoardYLayout.setHorizontalGroup(
            jPanelBoardYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanelBoardYLayout.setVerticalGroup(
            jPanelBoardYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelBoardX.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanelBoardXLayout = new javax.swing.GroupLayout(jPanelBoardX);
        jPanelBoardX.setLayout(jPanelBoardXLayout);
        jPanelBoardXLayout.setHorizontalGroup(
            jPanelBoardXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanelBoardXLayout.setVerticalGroup(
            jPanelBoardXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelBoardLayout = new javax.swing.GroupLayout(jPanelBoard);
        jPanelBoard.setLayout(jPanelBoardLayout);
        jPanelBoardLayout.setHorizontalGroup(
            jPanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBoardLayout.createSequentialGroup()
                .addComponent(jPanelBoardY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBoardX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBoardSquares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelBoardLayout.setVerticalGroup(
            jPanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoardLayout.createSequentialGroup()
                .addGroup(jPanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBoardSquares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBoardY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBoardX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelControls.setBackground(new java.awt.Color(51, 102, 0));

        jButtonExport.setBackground(new java.awt.Color(153, 153, 0));
        jButtonExport.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonExport.setText("Export");
        jButtonExport.setEnabled(false);

        jButtonLoadGame.setBackground(new java.awt.Color(153, 204, 0));
        jButtonLoadGame.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonLoadGame.setText("Load Game");
        jButtonLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadGameActionPerformed(evt);
            }
        });

        jButtonExit.setBackground(new java.awt.Color(204, 102, 0));
        jButtonExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Status");

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Available Housing spaces");

        jLabelLevel.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabelLevel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLevel.setText("Level");

        jButtonLevelUp.setBackground(new java.awt.Color(153, 204, 0));
        jButtonLevelUp.setText("Level Up +1");
        jButtonLevelUp.setEnabled(false);
        jButtonLevelUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLevelUpActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabelBuildingsAvailable.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabelBuildingsAvailable.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBuildingsAvailable.setText("Buildings");

        jComboBoxBuildings.setEnabled(false);

        jButtonPut.setText("Put");
        jButtonPut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPutActionPerformed(evt);
            }
        });

        jSpinnerX.setValue(1);
        jSpinnerX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinnerXMouseClicked(evt);
            }
        });
        jSpinnerX.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinnerXPropertyChange(evt);
            }
        });

        jLabelXCoord.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabelXCoord.setForeground(new java.awt.Color(255, 255, 255));
        jLabelXCoord.setText("X");

        jLabelYCoord.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabelYCoord.setForeground(new java.awt.Color(255, 255, 255));
        jLabelYCoord.setText("Y");

        jSpinnerY.setValue(1);
        jSpinnerY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinnerYMouseClicked(evt);
            }
        });

        jPanelImageSelectedBuilding.setBackground(new java.awt.Color(204, 255, 204));
        jPanelImageSelectedBuilding.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanelImageSelectedBuildingLayout = new javax.swing.GroupLayout(jPanelImageSelectedBuilding);
        jPanelImageSelectedBuilding.setLayout(jPanelImageSelectedBuildingLayout);
        jPanelImageSelectedBuildingLayout.setHorizontalGroup(
            jPanelImageSelectedBuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );
        jPanelImageSelectedBuildingLayout.setVerticalGroup(
            jPanelImageSelectedBuildingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );

        jButtonCargarDefensas.setText("Cargar Defensas");
        jButtonCargarDefensas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarDefensasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBuildingsAvailable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxBuildings, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelXCoord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelYCoord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonCargarDefensas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelImageSelectedBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBuildingsAvailable)
                    .addComponent(jComboBoxBuildings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelXCoord)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jSpinnerX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelYCoord)
                                .addComponent(jSpinnerY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCargarDefensas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelImageSelectedBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 51, 0));

        jLabelEnemies.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabelEnemies.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEnemies.setText("Enemies");

        jButtonCargarEnemigos.setBackground(new java.awt.Color(204, 204, 0));
        jButtonCargarEnemigos.setText("Cargar enemigos");
        jButtonCargarEnemigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarEnemigosActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEnemies)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButtonCargarEnemigos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelEnemies)
                .addGap(60, 60, 60)
                .addComponent(jButtonCargarEnemigos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButtonIniciarNueva.setText("Iniciar Nueva");
        jButtonIniciarNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarNuevaActionPerformed(evt);
            }
        });

        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("Name");

        javax.swing.GroupLayout jPanelControlsLayout = new javax.swing.GroupLayout(jPanelControls);
        jPanelControls.setLayout(jPanelControlsLayout);
        jPanelControlsLayout.setHorizontalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelName)
                        .addGap(134, 134, 134)
                        .addComponent(jLabelTitle)
                        .addGap(29, 29, 29)
                        .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelControlsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonLevelUp)))
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonExport, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonIniciarNueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLoadGame, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelControlsLayout.setVerticalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle)
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addComponent(jLabelLevel)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonLevelUp))
                    .addComponent(jLabelName))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(jButtonIniciarNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExport, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButtonLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanelGameLayout = new javax.swing.GroupLayout(jPanelGame);
        jPanelGame.setLayout(jPanelGameLayout);
        jPanelGameLayout.setHorizontalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addComponent(jPanelBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGameLayout.setVerticalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelBoard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabelTitle1.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        jLabelTitle1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle1.setText("Zombies war");

        javax.swing.GroupLayout jPanelTitlePaneLayout = new javax.swing.GroupLayout(jPanelTitlePane);
        jPanelTitlePane.setLayout(jPanelTitlePaneLayout);
        jPanelTitlePaneLayout.setHorizontalGroup(
            jPanelTitlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitlePaneLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabelTitle1))
        );
        jPanelTitlePaneLayout.setVerticalGroup(
            jPanelTitlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitlePaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelTitle1))
        );

        javax.swing.GroupLayout jPanelBGLayout = new javax.swing.GroupLayout(jPanelBG);
        jPanelBG.setLayout(jPanelBGLayout);
        jPanelBGLayout.setHorizontalGroup(
            jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGLayout.createSequentialGroup()
                .addComponent(jPanelGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelTitlePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBGLayout.setVerticalGroup(
            jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGLayout.createSequentialGroup()
                .addComponent(jPanelTitlePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadGameActionPerformed
       JFileChooser fc = new JFileChooser();
        int selection = fc.showOpenDialog(null);
        String route = "";
        if (selection == JFileChooser.APPROVE_OPTION) {
            //méFile fichero = fc.getSelectedFile();todo para leer el archivo y mostrarlo en el textArea
            File fichero = fc.getSelectedFile(); 
            route = fichero.getAbsolutePath();
           try {
               Game game = Game.load(route);
               game.getInstance().load(game);
               this.jButtonLevelUp.setEnabled(true);
               this.jComboBoxBuildings.setEnabled(true);
           } catch (IOException | ClassNotFoundException ex) {
               JOptionPane.showMessageDialog(null, "Error al cargar el juego"+ ex);
           }
        }
    }//GEN-LAST:event_jButtonLoadGameActionPerformed

    private void jButtonLevelUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLevelUpActionPerformed
       Game.getInstance().levelUp();
    }//GEN-LAST:event_jButtonLevelUpActionPerformed

    private void jSpinnerXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinnerXMouseClicked
        control.getBoard().refreshLabels();
        JLabel lnlCoordinates =  control.getBoard().getLabelsX().get((int) jSpinnerX.getValue()-1);
        JLabel lblYCoordinates =  control.getBoard().getLabelsY().get((int) jSpinnerY.getValue()-1);
        lnlCoordinates.setForeground(Color.BLUE);
        System.out.println("asdf");
    }//GEN-LAST:event_jSpinnerXMouseClicked

    private void jSpinnerYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinnerYMouseClicked
       
    }//GEN-LAST:event_jSpinnerYMouseClicked

    private void jSpinnerXPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinnerXPropertyChange
        
    }//GEN-LAST:event_jSpinnerXPropertyChange

    private void jButtonCargarDefensasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarDefensasActionPerformed

        String file = gameBuilder.getFile();
        try {
            gameBuilder.loadDefense(file);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Problems to load defenses "+ex);
        }
        actualizarComboBox();
        this.jButtonPut.setEnabled(true);
        this.jComboBoxBuildings.setEnabled(true);
        this.jButtonLevelUp.setEnabled(true);
        this.jSpinnerX.setEnabled(true);
        this.jSpinnerY.setEnabled(true);
    }//GEN-LAST:event_jButtonCargarDefensasActionPerformed
    private void actualizarComboBox (){
        jComboBoxBuildings.removeAllItems();
        for(Defense d : Game.getInstance().getDefenses()){
            jComboBoxBuildings.addItem(d.getName());
        }
        DefaultListModel model = new DefaultListModel();
        for(Enemy e: Game.getInstance().getEnemies()){
            model.addElement(e.getName());
        }
        jList1.setModel(model);
        jComboBoxBuildings.updateUI();
        jList1.updateUI();
    }
    private void jButtonCargarEnemigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarEnemigosActionPerformed

        String file = gameBuilder.getFile();
        try {
            gameBuilder.loadEnemy(file);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Problems to load characters "+ex);
        }
        actualizarComboBox();
        this.jButtonPut.setEnabled(true);
        this.jComboBoxBuildings.setEnabled(true);
        this.jButtonLevelUp.setEnabled(true);
        this.jSpinnerX.setEnabled(true);
        this.jSpinnerY.setEnabled(true);
    }//GEN-LAST:event_jButtonCargarEnemigosActionPerformed

    private void jButtonPutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPutActionPerformed
           
        int x  = (int) jSpinnerX.getValue();
        int y = (int) jSpinnerY.getValue();
        control.putBuilding(x, y,(String)jComboBoxBuildings.getSelectedItem());
        
    }//GEN-LAST:event_jButtonPutActionPerformed

    private void jButtonIniciarNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarNuevaActionPerformed
        String player =JOptionPane.showInputDialog("Digite su nombre: ");
        Game.getInstance().load(this.gameBuilder.load(player));
        jLabelName.setText("Player : "+player);
        this.jButtonCargarDefensas.setEnabled(false);
        this.jButtonCargarEnemigos.setEnabled(false);
        actualizarComboBox();
    }//GEN-LAST:event_jButtonIniciarNuevaActionPerformed
    private String getFile(){
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Guarde el archivo"); 
        int selection = fc.showSaveDialog(null);
        if (selection == JFileChooser.APPROVE_OPTION) {
            System.out.println("Get selected file "+fc.getSelectedFile().getAbsolutePath());
            return fc.getSelectedFile().getAbsolutePath();
        }
        return "";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIGAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIGAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIGAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIGAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIGAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargarDefensas;
    private javax.swing.JButton jButtonCargarEnemigos;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExport;
    private javax.swing.JButton jButtonIniciarNueva;
    private javax.swing.JButton jButtonLevelUp;
    private javax.swing.JButton jButtonLoadGame;
    private javax.swing.JButton jButtonPut;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBoxBuildings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBuildingsAvailable;
    private javax.swing.JLabel jLabelEnemies;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelXCoord;
    private javax.swing.JLabel jLabelYCoord;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBG;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanelBoardSquares;
    private javax.swing.JPanel jPanelBoardX;
    private javax.swing.JPanel jPanelBoardY;
    private javax.swing.JPanel jPanelControls;
    private javax.swing.JPanel jPanelGame;
    private javax.swing.JPanel jPanelImageSelectedBuilding;
    private javax.swing.JPanel jPanelTitlePane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerX;
    private javax.swing.JSpinner jSpinnerY;
    // End of variables declaration//GEN-END:variables

    private void pintarImagen(JPanel panel, String ruta){
        JLabel lbl = new JLabel();
        lbl.setBounds(0, 0, panel.getWidth(), panel.getHeight());
        ImageIcon imageIcon = new ImageIcon(ruta);
        Icon icon = new ImageIcon(imageIcon.getImage().getScaledInstance(
                                    lbl.getWidth(), 
                                    lbl.getHeight(), 
                                    Image.SCALE_DEFAULT));
        lbl.setIcon(icon);
        panel.add(lbl);
        
        this.repaint();
    }
    private void initBoard(){

        jPanelBoardSquares.setBackground(new Color(10,10,10,90));
        jPanelBoardX.setBackground(new Color(10, 10, 10, 10));
        jPanelBoardY.setBackground(new Color(10,10,10,10));
        jPanelBoard.setBackground(new Color(10,10,10,10));
        jPanelGame.setBackground(new Color(10,10 ,10 ,10));
        jPanelTitlePane.setBackground(new Color(10,10,10,120));
        control.getBoard().buildBoard(jPanelBoardX, jPanelBoardY, jPanelBoardSquares);
        control.getBoard().paintLifeTree(jPanelBoardSquares);
    }
}
