/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GameControl.BoardMarks.Board;
import GameControl.Settings;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.*;

/**
 *
 * @author Esteb
 */
public class GUIGAME extends javax.swing.JFrame {
    Board board = new Board();
    /**
     * Creates new form GUIGAME
     */
    public GUIGAME() {
        initComponents();
        setTitle("Compilador C"); 
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        initBoard();
        jPanelGame.setLayout( new GridLayout(1,2));
        jPanelGame.add(jPanelBoard);
        jPanelGame.add(jPanelControls);
        
        pintarImagen(jPanelBG, Settings.BACKGROUND);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanelBG = new javax.swing.JPanel();
        jPanelGame = new javax.swing.JPanel();
        jPanelBoard = new javax.swing.JPanel();
        jPanelBoardSquares = new javax.swing.JPanel();
        jPanelBoardY = new javax.swing.JPanel();
        jPanelBoardX = new javax.swing.JPanel();
        jPanelControls = new javax.swing.JPanel();
        jButtonExport = new javax.swing.JButton();
        jButtonLoadGame = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jButtonLevelUp = new javax.swing.JButton();
        jComboBoxBuildings = new javax.swing.JComboBox<>();
        jLabelBuildingsAvailable = new javax.swing.JLabel();
        jPanelTitlePane = new javax.swing.JPanel();
        jLabelTitle1 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelGame.setBackground(new java.awt.Color(255, 255, 204));

        jPanelBoard.setBackground(new java.awt.Color(102, 255, 51));

        jPanelBoardSquares.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanelBoardSquaresLayout = new javax.swing.GroupLayout(jPanelBoardSquares);
        jPanelBoardSquares.setLayout(jPanelBoardSquaresLayout);
        jPanelBoardSquaresLayout.setHorizontalGroup(
            jPanelBoardSquaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelBoardSquaresLayout.setVerticalGroup(
            jPanelBoardSquaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jPanelBoardY.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout jPanelBoardYLayout = new javax.swing.GroupLayout(jPanelBoardY);
        jPanelBoardY.setLayout(jPanelBoardYLayout);
        jPanelBoardYLayout.setHorizontalGroup(
            jPanelBoardYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanelBoardYLayout.setVerticalGroup(
            jPanelBoardYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelBoardX.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanelBoardXLayout = new javax.swing.GroupLayout(jPanelBoardX);
        jPanelBoardX.setLayout(jPanelBoardXLayout);
        jPanelBoardXLayout.setHorizontalGroup(
            jPanelBoardXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jPanelBoardXLayout.setVerticalGroup(
            jPanelBoardXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelBoardLayout = new javax.swing.GroupLayout(jPanelBoard);
        jPanelBoard.setLayout(jPanelBoardLayout);
        jPanelBoardLayout.setHorizontalGroup(
            jPanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBoardLayout.createSequentialGroup()
                .addComponent(jPanelBoardY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBoardX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBoardSquares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelBoardLayout.setVerticalGroup(
            jPanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBoardLayout.createSequentialGroup()
                .addGroup(jPanelBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBoardSquares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBoardY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBoardX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonExport.setText("Export");

        jButtonLoadGame.setText("Load Game");

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Status");

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Housing spaces: ");

        jLabelLevel.setFont(new java.awt.Font("Unispace", 0, 12)); // NOI18N
        jLabelLevel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLevel.setText("Level");

        jButtonLevelUp.setText("Level Up +1");

        jLabelBuildingsAvailable.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabelBuildingsAvailable.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBuildingsAvailable.setText("Buildings");

        javax.swing.GroupLayout jPanelControlsLayout = new javax.swing.GroupLayout(jPanelControls);
        jPanelControls.setLayout(jPanelControlsLayout);
        jPanelControlsLayout.setHorizontalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabelTitle)
                .addGap(29, 29, 29)
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonLevelUp)))
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1))
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelBuildingsAvailable)
                .addGap(39, 39, 39)
                .addComponent(jComboBoxBuildings, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButtonExport, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jButtonLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelControlsLayout.setVerticalGroup(
            jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlsLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle)
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addComponent(jLabelLevel)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonLevelUp)))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBuildingsAvailable)
                    .addGroup(jPanelControlsLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jComboBoxBuildings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(529, 529, 529)
                .addGroup(jPanelControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExport, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLoadGame, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanelGameLayout = new javax.swing.GroupLayout(jPanelGame);
        jPanelGame.setLayout(jPanelGameLayout);
        jPanelGameLayout.setHorizontalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addComponent(jPanelBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        jPanelGameLayout.setVerticalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelGameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelTitle1.setFont(new java.awt.Font("Unispace", 0, 36)); // NOI18N
        jLabelTitle1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle1.setText("Zombies war");

        javax.swing.GroupLayout jPanelTitlePaneLayout = new javax.swing.GroupLayout(jPanelTitlePane);
        jPanelTitlePane.setLayout(jPanelTitlePaneLayout);
        jPanelTitlePaneLayout.setHorizontalGroup(
            jPanelTitlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitlePaneLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabelTitle1))
        );
        jPanelTitlePaneLayout.setVerticalGroup(
            jPanelTitlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitlePaneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelTitle1))
        );

        javax.swing.GroupLayout jPanelBGLayout = new javax.swing.GroupLayout(jPanelBG);
        jPanelBG.setLayout(jPanelBGLayout);
        jPanelBGLayout.setHorizontalGroup(
            jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGLayout.createSequentialGroup()
                .addComponent(jPanelGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelTitlePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBGLayout.setVerticalGroup(
            jPanelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBGLayout.createSequentialGroup()
                .addComponent(jPanelTitlePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIGAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIGAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIGAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIGAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIGAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonExport;
    private javax.swing.JButton jButtonLevelUp;
    private javax.swing.JButton jButtonLoadGame;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBoxBuildings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBuildingsAvailable;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JPanel jPanelBG;
    private javax.swing.JPanel jPanelBoard;
    private javax.swing.JPanel jPanelBoardSquares;
    private javax.swing.JPanel jPanelBoardX;
    private javax.swing.JPanel jPanelBoardY;
    private javax.swing.JPanel jPanelControls;
    private javax.swing.JPanel jPanelGame;
    private javax.swing.JPanel jPanelTitlePane;
    // End of variables declaration//GEN-END:variables

    private void pintarImagen(JPanel panel, String ruta){
        JLabel lbl = new JLabel();
        lbl.setBounds(0, 0, panel.getWidth(), panel.getHeight());
        ImageIcon imageIcon = new ImageIcon(ruta);
        Icon icon = new ImageIcon(imageIcon.getImage().getScaledInstance(
                                    lbl.getWidth(), 
                                    lbl.getHeight(), 
                                    Image.SCALE_DEFAULT));
        lbl.setIcon(icon);
        panel.add(lbl);
        
        this.repaint();
    }
    private void initBoard(){

        jPanelBoardSquares.setBackground(new Color(10,10,10,90));
        jPanelControls.setBackground(new Color(10, 10, 10, 10));
        jPanelBoardX.setBackground(new Color(10, 10, 10, 10));
        jPanelBoardY.setBackground(new Color(10,10,10,10));
        jPanelBoard.setBackground(new Color(10,10,10,10));
        jPanelGame.setBackground(new Color(10,10 ,10 ,10));
        jPanelTitlePane.setBackground(new Color(10,10,10,120));
        board.buildBoard(jPanelBoardX, jPanelBoardY, jPanelBoardSquares);
    }
}
